# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      types: [py]
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending
          - id: check-toml
          - id: check-yaml

    - repo: https://github.com/psf/black
      rev: 22.1.0
      types: [ python ]
      hooks:
        - id: black
          additional_dependencies: ['click==8.0.4']
          args: [ --safe ]

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            args: [--config, setup.cfg]
