name: Test

on:
  push:
    branches: [master, dev]
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:

  code-change:
    runs-on: ubuntu-latest
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '[
          "docs/**",
          ".github/**",
          ".social/**",
          "README.md",
          "CHANGELOG.md",
          "CONTRIBUTING.md",
          ".pre-commit-config.yaml",
          ".readthedocs.yaml",
          "pyproject.toml"
          ]'
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}


  tests:
    needs: code-change
    if: ${{ needs.code-change.outputs.should_skip != 'true'}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.10"]  # check oldest and latest supported version
        other-os: [false]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.other-os }}  # don't cancel due to OS specific failures
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and install
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run tests
      run: |
        pytest cmpy/ --cov=cmpy --cov-report=xml -v
